### ISSUE TITLE
In python3, calling next() of iternext fails with segment fault

### ISSUE THREAD

**Issue by hamukazu** [dw/py-lmdb#105]
In python3, the following code fails with a segment fault:

    env=lmdb.Environment("/path/to/db")
    txn=env.begin()
    cur=txn.cursor()
    ite=cur.iternext()
    ite.next()

The correct method for an iterator in python3 is `__next__()`, so it is OK that it doesn't work, but just dying with a segment fault is inconvenient for troubleshooting.

**Comment by dw** [comment]
Which version of Python 3, which architecture, which OS, which version of py-lmdb, and which variant (cffi/CPython)?

**Comment by dw** [comment]
Hello,

It looks like a reference counting bug. In the meantime, please:

````
pip uninstall lmdb
LMDB_FORCE_CFFI=1 pip install --no-cache-dir lmdb
````

I'll get this fixed shortly. Sorry for the inconvenience.

**Comment by dw** [comment]
Hi there,

This will be fixed in the next release. Note that calling `iterator.next()` is not the same as calling `next(iterator)`. The former expects a method named `next()` to be defined, the latter for a built-in object expects its `.tp_iternext` member to be defined. Additionally on Python 3, the presence of `.tp_iternext` will also cause `__next__` to be defined by Python `typeobject.c`.

As a workaround for the current release, please do not call `.next()` directly.
