### ISSUE TITLE
Multiples processes writing same database

### ISSUE THREAD

**Issue by carlopires** [dw/py-lmdb#114]
I'm having some calls to Transaction getting stalled:
```
with env.begin(write=True) as txn
    txn.put('somename', 'somedata')
```
I have multiples processes trying to write into same database.

So, If I want to have multiples processes writing the database should I need to implement a server side or some kind of IPC sync to avoid multiples writers trying to write the database at same time?

**Comment by dw** [comment]
Hi Carlo,

LMDB is single-writer multi-reader by default, there can only be one active write transaction at a time, attempts to start additional write transactions will stall until the first one completes.

I'm guessing the problem is that your write transactions are long-lived, please try refactoring your code to avoid such long writes
