### ISSUE TITLE
lmdb.NotFoundError

### ISSUE THREAD

**Issue by nyov** [dw/py-lmdb#122]
`lmdb.NotFoundError` documentation says it is raised when "No matching key/data pair found."

From that description I though it would be raised when `txn.get()` or `curs.get()` keys do not exist, however that is not so. Instead `None` is returned (`buffers=False`):
```py
with env.begin() as txn:
    try:
        val = txn.get('nonexistingkey')
    except lmdb.NotFoundError:
        raise # not happening
    print (val) # is None
```

After checking the [testcases](https://github.com/dw/py-lmdb/blob/c5a38b4c7cc82506f869adcd0ceb9746bd3f1977/tests/env_test.py#L705), it only ever seems to be raised for `lmdb.open_db()`?
Is this intended?

### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    0.89

### py-lmdb Installation Method

    pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

    (0, 9, 18)

**Comment by dw** [comment]
Hi there,

This is basically a documentation bug, I believe it is an expected behaviour that searching for a non-existent key in a database is a non-exceptional situation, and should not be require adverse program control flow. Exceptions are much more expensive than sentinel values, and in the common case produce more boilerplate code than need otherwise exist.

Do you suppose updating the docstring is sufficient? Those exception classes are essentially a 1:1 mapping to the underlying LMDB error codes. It is also possible we could replace the sole use of that exception with e.g. IOError and simplify the binding.

**Comment by nyov** [comment]
I think clarifying the docstring should be sufficient, depending on what the Exception's goal is (I haven't dived into lmdb's sources). If it only represents a sub-db/named-db not-found error, renaming it could also make sense (if such an API change is still reasonably possible now).

And I understand that Exception handling is more expensive, but this differs from the common python way of raising `KeyError` on non-existing dict-like object keys and having `None` values returned for empty (but existing) keys.
I was simply unaware, but I see now that `None` values are stored/returned as empty bytestrings.

**Comment by nyov** [comment]
Thank you!
