### ISSUE TITLE
lmdb.open name collision when using a wildcard import

### ISSUE THREAD

**Issue by ZhukovAlexander** [dw/py-lmdb#135]
### Affected Operating Systems

* Linux
* Windows
* BSD
* [Other]

### Affected py-lmdb Version

   latest

### py-lmdb Installation Method

    any

### Using bundled or distribution-provided LMDB library?

any

### Describe Your Problem

```python
from lmdb import *
``` 
will shadow ```__builtins__.open``` silently

### Errors/exceptions Encountered

e.g.

```python
>>> open('test', 'w')
<open file 'test', mode 'w' at 0x1079d4f60>
>>> from lmdb import *
>>> open('test', 'w')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Integer argument exceeds limit.
>>>
```
Clearly, when using a wildcard import there is no way to use ```as``` clause to prevent this.

**Comment by dw** [comment]
Hi Alexander, how does this look?

I have removed open from ``__all__`` in cffi.py, and defined a new ``__all__`` for cpython.so that matches the copy in cffi.py.

The net result is "from lmdb import *" does not shadow open, however lmdb.open remains avaiable. For users that want to use ``import *``, the ``Environment`` alias can still be used, e.g.:

````
import lmdb
env = lmdb.open(...)

from lmdb import *
env = Environment(...)
````

I can't think of any other solution except prefixing all the function and type names, which I'm unwilling to do as IMHO it encourages people to ignore namespaces and produces less readable code overall

**Comment by ZhukovAlexander** [comment]
@dw , 100% agree that people should respect namespaces. I think your solution is the cleanest one and should work perfectly fine.
