### ISSUE TITLE
Readonly=True does not seem to work for non-root user

### ISSUE THREAD

**Issue by CallMeFoxie** [dw/py-lmdb#141]
### Affected Operating Systems
* Linux
(cannot test on anything else)

### Affected py-lmdb Version
0.92

### py-lmdb Installation Method
pip

### Using bundled or distribution-provided LMDB library?
Bundled

### Distribution name and LMDB library version
>>> print(lmdb.version())
(0, 9, 18)

### Machine "free -m" output
16GB RAM+, irrelevant, tested on multiple machines

### Other important machine info
tested both with RHEL6 and RHEL7 kernel, python 3.4.2 (current Debian Jessie Stable)

### Describe Your Problem
It seems that setting readonly=True has no effect for non-root users, unsure what is actually happening:
$ id
uid=0(root) gid=0(root) groups=0(root)
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmdb
>>> lmdb.open('/tmp/lmdb', readonly=True)
<Environment object at 0x7fb6e4dacdb0>

whereas
$ id
uid=111(sznlogy) gid=65534(nogroup) groups=65534(nogroup)
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmdb
>>> lmdb.open('/tmp/lmdb', readonly=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lmdb.ReadonlyError: /tmp/lmdb: Permission denied

but the user can list the directory and its files fine, can even cat the contents:
$ ls -la /tmp/lmdb/
total 1308
dr-xr-xr-x  2 root root      36 Nov 21 15:20 .
drwxrwxrwt 38 root root    4096 Nov 21 16:58 ..
-r--r--r--  1 root root 1327104 Nov 21 15:20 data.mdb
-r--r--r--  1 root root    8192 Nov 21 16:58 lock.mdb

### Describe What You Expected To Happen
open the lmdb in read only mode

### Describe What Happened Instead
ReadonlyError (as described)

**Comment by dw** [comment]
Hi there,

In order to participate in MVCC, even a read-only environment must still have write access to the database lock file. In other words, LMDB does not quite follow the UNIX permissions model by default, and you must choose to either make the lock file writeable (probably a bad idea), disable LMDB's internally locking entirely, or perhaps setup a common UNIX group that is granted write access to the lock file.

See the section "Synchronization" of the Postfix <a href="http://www.postfix.org/lmdb_table.5.html">lmdb_table manual page</a> for an example implementation of disabling LMDB's locking entirely.

**Comment by patter001** [comment]
In windows, I found that can use lock=False, readonly=True and open the
database if it is a readonly file....(also assumes specifying the mapsize=
file size on windows).

I am not sure about linux.

Sadly, I just discovered this only works with the released lmdb and not
with the sparse win32patch :(

**Comment by CallMeFoxie** [comment]
I've tested it about an hour ago on linux with lock=False and it seems to work that way as well.

Thanks!
