### ISSUE TITLE
Set default map_size to the size of disk partition, max 2G on 32bit system.

### ISSUE THREAD

**Issue by yihuang** [dw/py-lmdb#76]
I think this is reasonable for most user, you can see how redis-nds does this: `https://github.com/yihuang/redis/blob/nds-2.6/src/nds.c#L170`, how do you think?

**Comment by dw** [comment]
Hi yihuang,

I'm closing this ticket, since it is not possible to support the behaviour on either Windows (as we recently learned) or OS X (as mentioned in 2014), leaving only Linux where the default behaviour would be sensible. In all other cases, a maximum size would need to be configured. This means the behaviour of the exported API would differ across OS, which is not acceptable.
