### ISSUE TITLE
Which lmdb classes are thread safe ?

### ISSUE THREAD

**Issue by stephane-martin** [dw/py-lmdb#89]
Hello,

I understand by the other issues that in an async app (I use Tornado), i should defer the read and write lmdb operations in a background thread, because they are obvisouly blocking.

Should I create new instances of lmdb classiques inside the background thread ? Or it OK to share an Environment, a Transaction or a Cursor instance between 2 concurrent threads ?

(By the way, i just love your bindings, i have been looking for something like this for years.)

Stephane

**Comment by dw** [comment]
Hi Stephane,

The most definitive answer can be found by searching for the word 'thread' in https://github.com/dw/py-lmdb/blob/master/lib/lmdb.h .. but in summary, roughly:

* Most objects can be safely called by a single caller from a single thread, and usually it only makes sense to to have a single caller, except in the case of ``Environment``.
* Most ``Environment`` methods are thread-safe, and may be called concurrently, except for ``close()``.
* A write ``Transaction`` can only be used from the thread it was created on.
* A read-only ``Transaction`` can move across threads, but it cannot be used concurrently from multiple threads.
* ``Cursor`` is not thread-safe, but it does not make sense to use it on any thread except the thread that currently owns its associated ``Transaction``

Going to keep this bug open, since this is basically a docs problem that I need to fix :)

**Comment by stephane-martin** [comment]
nice, thanks!
